version: '3'
services:
  web:
    container_name: buildy-apache
    build: ./config/web
    ports :
      - "3000:80"
    volumes:
     - ./www:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
     - postgres
  
  postgres:
    container_name: buildy-db
    image: postgres:9.6 
    env_file:
    - ./config/env 
    restart: always
  
  pgadmin:
    container_name: buildy-admin
    image: fenglc/pgadmin4
    restart: always
    env_file:
      - ./config/env
    depends_on:
      - postgres
    ports:
      - 5050:5050