"/":
  controller: Pages
  action: default
  method: "get"

"/test":
  controller: Pages
  action: test
  method: "get"

"/liste_des_utilisateurs":
  controller: Users
  action: default
  method: "get"

"/ajouter_un_utilisateur":
  controller: Users
  action: add
  method: "post"

"/enregister_un_utilisateur":
  controller: Users
  action: save
  method: "post"

"/connexion":
  controller: Users
  action: login
  method: "post"

"/mot_de_passe_oublie":
  controller: Users
  action: forgetPassword
  method: "get"

# ######################################## EN ######################################

"/users":
  controller: Users
  action: default
  method: "get"

"/not_found":
  controller: Pages
  action: notFound
  method: "post"

"/add_users":
  controller: Users
  action: add
  method: "post"
"/register":
  controller: Users
  action: save
  method: "post"

"/connection":
  controller: Users
  action: login
  method: "post"

"/forget_password":
  controller: Users
  action: forgetPassword
  method: "get"