"/":
  controller: Pages
  action: default
  method: "GET"

"/test":
  controller: Pages
  action: test
  method: "GET"

"/component":
  controller: Pages
  action: component
  method: "GET"

"/not_found":
  controller: Pages
  action: notFound
  method: "POST"

"/add_users":
  controller: Users
  action: add
  method: "POST"

"/connection":
  controller: Users
  action: login
  method: "POST"

"/forget_password":
  controller: Users
  action: forgetPassword
  method: "GET"

"/about":
  controller: Pages
  action: about
  method: "GET"

"/legal":
  controller: Pages
  action: legal
  method: "GET"

"/dashboard":
  controller: Pages
  action: dashboard
  method: "GET"

"/mysite":
  controller: Pages
  action: mySite
  method: "GET"

"/pages/{?}":
  controller: Pages
  action: page
  method: "GET"

"/addpage":
  controller: Pages
  action: addPage
  method: "GET"

"/modifypage":
  controller: Pages
  action: editPage
  method: "GET"

"/home":
  controller: Pages
  action: home
  method: "GET"


"/saveuser":
  controller: Users
  action: save
  method: "POST"
########################################## MODELS READ ROUTES #############################
"/articles":
  controller: Articles
  action: getArticlesView
  method: "GET"

"/cards":
  controller: Cards
  action: getCardsView
  method: "GET"

"/tournaments":
  controller: Tournaments
  action: getTournamentsView
  method: "GET"
########################################## MODELS WRITE ROUTES ############################
"/register":
  controller: Users
  action: getRegisterForm
  method: "POST"

"/writearticle":
  controller: Articles
  action: getArticlesForm
  method: "POST"

"/createtournaments":
  controller: Tournaments
  action: getTournamentsForm
  method: "GET"

"/createdeck":
  controller: Decks
  action: getDecksForm
  method: "GET"

"/filldeck":
  controller: Decks
  action: getLegalCards
  method: "GET"

"/savedeck":
  controller: Decks
  action: getSaveConfirmation
  method: "POST"

########################################## CRUD ROUTES #############################

"/list/{!}":
  controller: ""
  action: list
  method: "GET"

"/delete/{!}":
  controller: ""
  action: delete
  method: "GET"

"/edit/{!}":
  controller: ""
  action: edit
  method: "GET"

"/update":
  controller: ""
  action: update
  method: POST

