######## HOME #######

"/":
  controller: Home
  action: default
  method: "GET"

"/mysite/page":
  controller: Pages
  action: default
  method: "GET"

"/mysite/page/edit":
  controller: Pages
  action: detail
  method: "GET"

"/mysite/page/edit/insert":
  controller: Pages
  action: insertContent
  method: "POST"

"/mysite/addpage":
  controller: Pages
  action: addView
  method: "GET"

"/mysite/page/save":
  controller: Pages
  action: save
  method: "POST"

"/mysite":
  controller: Pages
  action: mySite
  method: "GET"

"/mysite/cards":
  controller: Cards
  action: backCards
  method: "GET"

########### LEGAL CONTACT ABOUT ##############

"/mysite/legal":
  controller: Home
  action: getLegal
  method: "GET"

"/mysite/contact":
  controller: Home
  action: getContact
  method: "GET"

"/mysite/about":
  controller: Home
  action: getAbout
  method: "GET"

"/download":
  controller: AdminCards
  action: download
  method: "POST"

"/get_buildy":
  controller: Pages
  action: getBuildy
  method: "POST"

"/set_buildy":
  controller: Pages
  action: setBuildy
  method: "POST"


################### ADMIN CRUDS ###################

### CARDS ###
"/dashboard/admin/cards":
  controller: AdminCards
  action: default
  method: "GET"

### TOURNAMENTS ###
"/dashboard/admin/tournaments":
  controller: AdminTournaments
  action: default
  method: "GET"

"/dashboard/admin/tournaments/delete":
  controller: AdminTournaments
  action: deleteTournament
  method: "POST"

"/dashboard/admin/tournaments/save":
  controller: AdminTournaments
  action: saveTournament
  method: "POST"

### ARTICLES ###
"/dashboard/admin/articles":
  controller: AdminArticles
  action: default
  method: "GET"

"/dashboard/admin/articles/delete":
  controller: AdminArticles
  action: deleteArticle
  method: "POST"

"/dashboard/admin/articles/save":
  controller: AdminArticles
  action: saveArticle
  method: "POST"

### USERS ###
"/dashboard/admin/users":
  controller: AdminUsers
  action: default
  method: "GET"

"/dashboard/admin/users/delete":
  controller: AdminUsers
  action: deleteUser
  method: "POST"

"/dashboard/admin/users/save":
  controller: AdminUsers
  action: saveUser
  method: "POST"

### DECKS ###
"/dashboard/admin/decks":
  controller: AdminDecks
  action: default
  method: "GET"

"/dashboard/admin/decks/delete":
  controller: AdminDecks
  action: deleteDeck
  method: "POST"

"/dashboard/admin/decks/save":
  controller: AdminDecks
  action: saveDeck
  method: "POST"

### COMMENTS ###
"/dashboard/admin/comments":
  controller: AdminComments
  action: default
  method: "GET"

"/dashboard/admin/comments/delete":
  controller: AdminComments
  action: deleteComment
  method: "POST"

"/dashboard/admin/comments/save":
  controller: AdminComments
  action: saveComment
  method: "POST"

### PAGES ###
"/dashboard/admin/pages":
  controller: AdminPages
  action: default
  method: "GET"
  
"/dashboard/admin/pages/delete":
  controller: AdminPages
  action: deletePage
  method: "POST"

"/dashboard/admin/pages/save":
  controller: AdminPages
  action: savePage
  method: "POST"

######## DASHBOARD #######
"/dashboard":
  controller: Dashboard
  action: default
  method: "GET"

"/dashboard/stats":
  controller: Dashboard
  action: getStats
  method: "GET"


######################### FRONT SITE #########################

"/site":
  controller: Site
  action: default
  method: "GET"

"/site/cards":
  controller: Cards
  action: frontCards
  method: "GET"

"/site/page":
  controller: Pages
  action: getPage
  method: "GET"

"/site/register":
  controller: Users
  action: getRegisterView
  method: "GET"

"/site/login":
  controller: Users
  action: getLoginView
  method: "GET"

"/site/save":
  controller: Users
  action: save
  method: "POST"

"/site/connexion":
  controller: Users
  action: connexion
  method: "POST"

"/site/deconnexion":
  controller: Users
  action: deconnexion
  method: "POST"

"/site/article/save":
  controller: Articles
  action: save
  method: "POST"

"/site/tournament/save":
  controller: Tournaments
  action: save
  method: "POST"

"/site/deck/save":
  controller: Decks
  action: save
  method: "POST"

"/site/articles/get":
  controller: Articles
  action: getAllArticles
  method: "GET"



################## DYNAMIQUE PAGES #######################



