"/":
  controller: Pages
  action: default
  method: "GET"

"/test":
  controller: Pages
  action: test
  method: "GET"

# ######################################## EN ######################################

"/not_found":
  controller: Pages
  action: notFound
  method: "POST"

"/add_users":
  controller: Users
  action: add
  method: "POST"

"/connection":
  controller: Users
  action: login
  method: "POST"

"/forget_password":
  controller: Users
  action: forgetPassword
  method: "GET"

"/load_cards":
  controller: Cards
  action: download
  method: "POST"

"/about":
  controller: Pages
  action: about
  method: "GET"

"/legal":
  controller: Pages
  action: legal
  method: "GET"

"/dashboard":
  controller: Pages
  action: dashboard
  method: "GET"

"/mySite":
  controller: Pages
  action: mySite
  method: "GET"

"/pages/{?}":
  controller: Pages
  action: page
  method: "GET"

"/modifyPage":
  controller: Pages
  action: modifyPage
  method: "GET"

"/addPage":
  controller: Pages
  action: addPage
  method: "GET"

"/articles":
  controller: Articles
  action: getArticlesView
  method: "GET"

"/cards":
  controller: Cards
  action: getCardsView
  method: "GET"

"/users":
  controller: Users
  action: getUsersView
  method: "GET"

"/tournaments":
  controller: Tournaments
  action: getTournamentsView
  method: "GET"

"/home":
  controller: Pages
  action: home
  method: "GET"

"/register":
  controller: Users
  action: getRegisterForm
  method: "POST"

"/saveUser":
  controller: Users
  action: save
  mothod: "POST"

"/list/{!}":
  controller: ""
  action: list
  method: "GET"

"/delete/{!}":
  controller: ""
  action: delete
  method: "GET"

"/edit/{!}":
  controller: ""
  action: edit
  method: "GET"