"/":
  controller: Pages
  action: default
  method: "GET"

"/test":
  controller: Pages
  action: test
  method: "GET"

"/liste_des_utilisateurs":
  controller: Users
  action: default
  method: "GET"

"/ajouter_un_utilisateur":
  controller: Users
  action: add
  method: "POST"

"/enregister_un_utilisateur":
  controller: Users
  action: save
  method: "POST"

"/connexion":
  controller: Users
  action: login
  method: "POST"

"/mot_de_passe_oublie":
  controller: Users
  action: forgetPassword
  method: "GET"

# ######################################## EN ######################################

"/users":
  controller: Users
  action: default
  method: "GET"

"/not_found":
  controller: Pages
  action: notFound
  method: "POST"

"/add_users":
  controller: Users
  action: add
  method: "POST"
"/register":
  controller: Users
  action: save
  method: "POST"

"/connection":
  controller: Users
  action: login
  method: "POST"

"/forget_password":
  controller: Users
  action: forgetPassword
  method: "GET"

"/load_cards":
  controller: Card
  action: download
  method: "POST"
