###### ADMIN ######

"/admin":
  controller: Home
  action: default
  method: "GET"
  allow: [ADMIN]


"/admin/mysite":
  controller: Pages
  action: mySite
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/page":
  controller: Pages
  action: default
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/page/edit":
  controller: Pages
  action: detail
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/page/edit/insert":
  controller: Pages
  action: insertContent
  method: "POST"
  allow: [ADMIN]

"/admin/mysite/page/save":
  controller: Pages
  action: save
  method: "POST"
  allow: [ADMIN]

"/admin/mysite/addpage":
  controller: Pages
  action: addView
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/cards":
  controller: Cards
  action: backCards
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/legal":
  controller: Home
  action: getLegal
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/contact":
  controller: Home
  action: getContact
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/about":
  controller: Home
  action: getAbout
  method: "GET"
  allow: [ADMIN]

"/admin/download":
  controller: AdminCards
  action: download
  method: "POST"
  allow: [ADMIN]



################### ADMIN CRUDS ###################

### CARDS ###
"/admin/dashboard/cards":
  controller: AdminCards
  action: default
  method: "GET"
  allow: [ADMIN]

### TOURNAMENTS ###
"/admin/dashboard/tournaments":
  controller: AdminTournaments
  action: default
  method: "GET"
  allow: [ADMIN]

"/admin/dashboard/tournaments/delete":
  controller: AdminTournaments
  action: deleteTournament
  method: "POST"
  allow: [ADMIN]

"/admin/dashboard/tournaments/save":
  controller: AdminTournaments
  action: saveTournament
  method: "POST"
  allow: [ADMIN]

### ARTICLES ###
"/admin/dashboard/articles":
  controller: AdminArticles
  action: default
  method: "GET"
  allow: [ADMIN]

"/admin/dashboard/articles/delete":
  controller: AdminArticles
  action: deleteArticle
  method: "POST"
  allow: [ADMIN]

"/admin/dashboard/articles/save":
  controller: AdminArticles
  action: saveArticle
  method: "POST"
  allow: [ADMIN]

### USERS ###
"/admin/dashboard/users":
  controller: AdminUsers
  action: default
  method: "GET"
  allow: [ADMIN]

"/admin/dashboard/users/delete":
  controller: AdminUsers
  action: deleteUser
  method: "POST"
  allow: [ADMIN]

"/admin/dashboard/users/save":
  controller: AdminUsers
  action: saveUser
  method: "POST"
  allow: [ADMIN]

### DECKS ###
"/admin/dashboard/decks":
  controller: AdminDecks
  action: default
  method: "GET"
  allow: [ADMIN]

"/admin/dashboard/decks/delete":
  controller: AdminDecks
  action: deleteDeck
  method: "POST"
  allow: [ADMIN]

"/admin/dashboard/decks/save":
  controller: AdminDecks
  action: saveDeck
  method: "POST"
  allow: [ADMIN]

### COMMENTS ###
"/admin/dashboard/comments":
  controller: AdminComments
  action: default
  method: "GET"
  allow: [ADMIN]

"/admin/dashboard/comments/delete":
  controller: AdminComments
  action: deleteComment
  method: "POST"
  allow: [ADMIN]

"/admin/dashboard/comments/save":
  controller: AdminComments
  action: saveComment
  method: "POST"
  allow: [ADMIN]

### PAGES ###
"/admin/dashboard/pages":
  controller: AdminPages
  action: default
  method: "GET"
  allow: [ADMIN]

"/admin/dashboard/pages/delete":
  controller: AdminPages
  action: deletePage
  method: "POST"
  allow: [ADMIN]

"/admin/dashboard/pages/save":
  controller: AdminPages
  action: savePage
  method: "POST"
  allow: [ADMIN]

######## DASHBOARD #######
"/admin/dashboard":
  controller: Dashboard
  action: default
  method: "GET"
  allow: [ADMIN]

"/admin/dashboard/stats":
  controller: Dashboard
  action: getStats
  method: "GET"
  allow: [ADMIN]


######################### FRONT SITE #########################
"/":
  controller: Site
  action: default
  method: "GET"

"/site":
  controller: Site
  action: default
  method: "GET"

"/site/cards":
  controller: Cards
  action: frontCards
  method: "GET"

"/site/register":
  controller: Users
  action: getRegisterView
  method: "GET"

"/site/login":
  controller: Users
  action: getLoginView
  method: "GET"

"/site/save":
  controller: Users
  action: save
  method: "POST"

"/site/connexion":
  controller: Users
  action: connexion
  method: "POST"

"/site/deconnexion":
  controller: Users
  action: deconnexion
  method: "POST"

"/site/article/save":
  controller: Articles
  action: save
  method: "POST"

"/site/tournament/save":
  controller: Tournaments
  action: save
  method: "POST"

"/site/deck/save":
  controller: Decks
  action: save
  method: "POST"

"/site/articles/get":
  controller: Articles
  action: getAllArticles
  method: "GET"



################## DYNAMIQUE PAGES #######################



