###### ADMIN ######

"/admin":
  controller: Home
  action: default
  method: "GET"
  allow: [ADMIN]


"/admin/mysite":
  controller: Pages
  action: mySite
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/page":
  controller: Pages
  action: default
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/page/edit":
  controller: Pages
  action: detail
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/page/edit/insert":
  controller: Pages
  action: insertContent
  method: "POST"
  allow: [ADMIN]

"/admin/mysite/page/save":
  controller: Pages
  action: save
  method: "POST"
  allow: [ADMIN]

"/admin/mysite/addpage":
  controller: Pages
  action: addView
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/cards":
  controller: Cards
  action: backCards
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/legal":
  controller: Home
  action: getLegal
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/contact":
  controller: Home
  action: getContact
  method: "GET"
  allow: [ADMIN]

"/admin/mysite/about":
  controller: Home
  action: getAbout
  method: "GET"
  allow: [ADMIN]

"/admin/download":
  controller: AdminCards
  action: download
  method: "POST"
  allow: [ADMIN]



################### ADMIN CRUDS ###################

### CARDS ###
"/admin/dashboard/cards":
  controller: AdminCards
  action: default
  method: "GET"
  allow: [ADMIN, MODERATOR]

### TOURNAMENTS ###
"/admin/dashboard/tournaments":
  controller: AdminTournaments
  action: default
  method: "GET"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/tournaments/delete":
  controller: AdminTournaments
  action: deleteTournament
  method: "POST"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/tournaments/save":
  controller: AdminTournaments
  action: saveTournament
  method: "POST"
  allow: [ADMIN, MODERATOR]

### ARTICLES ###
"/admin/dashboard/articles":
  controller: AdminArticles
  action: default
  method: "GET"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/users":
  controller: AdminUsers
  action: default
  method: "GET"
  allow: [ADMIN]
  redirect: "/admin/dashboard"

"/admin/dashboard/users/delete":
  controller: AdminUsers
  action: deleteUser
  method: "POST"
  allow: [ADMIN]
  redirect: "/admin/dashboard"

"/admin/dashboard/users/save":
  controller: AdminUsers
  action: saveUser
  method: "POST"
  allow: [ADMIN]
  redirect: "/admin/dashboard"

### DECKS ###
"/admin/dashboard/decks":
  controller: AdminDecks
  action: default
  method: "GET"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/decks/delete":
  controller: AdminDecks
  action: deleteDeck
  method: "POST"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/decks/save":
  controller: AdminDecks
  action: saveDeck
  method: "POST"
  allow: [ADMIN, MODERATOR]

### COMMENTS ###
"/admin/dashboard/comments":
  controller: AdminComments
  action: default
  method: "GET"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/comments/delete":
  controller: AdminComments
  action: deleteComment
  method: "POST"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/comments/save":
  controller: AdminComments
  action: saveComment
  method: "POST"
  allow: [ADMIN, MODERATOR]

### PAGES ###
"/admin/dashboard/pages":
  controller: AdminPages
  action: default
  method: "GET"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/pages/delete":
  controller: AdminPages
  action: deletePage
  method: "POST"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/pages/save":
  controller: AdminPages
  action: savePage
  method: "POST"
  allow: [ADMIN, MODERATOR]

######## DASHBOARD #######
"/admin/dashboard":
  controller: Dashboard
  action: default
  method: "GET"
  allow: [ADMIN, MODERATOR]

"/admin/dashboard/stats":
  controller: Dashboard
  action: getStats
  method: "GET"
  allow: [ADMIN, MODERATOR]


######################### FRONT SITE #########################
"/":
  controller: Site
  action: default
  method: "GET"

"/site":
  controller: Site
  action: default
  method: "GET"

"/site/cards":
  controller: Cards
  action: frontCards
  method: "GET"

"/site/register":
  controller: User
  action: getRegisterView
  method: "GET"

"/site/login":
  controller: Users
  action: getLoginView
  method: "GET"

"/site/save":
  controller: Users
  action: save
  method: "POST"

"/site/connexion":
  controller: Users
  action: connexion
  method: "POST"

"/site/deconnexion":
  controller: Users
  action: deconnexion
  method: "POST"

"/site/profile":
  controller: Users
  action: getProfile
  method: "GET"
  allow: [ADMIN, MODERATOR, USER]
  redirect: "/site/login"

#  "site/profile/edit":
#    controller: Users
#    action: editProfile
#    method: "POST"

"/site/article/save":
  controller: Articles
  action: saveArticle
  method: "POST"
  allow: [ADMIN, MODERATOR, USER]
  redirect: "/site/login"

"/site/tournament/save":
  controller: Tournaments
  action: saveTournament
  method: "POST"
  allow: [ADMIN, MODERATOR, USER]
  redirect: "/site/login"


"/site/deck/save":
  controller: Decks
  action: saveDeck
  method: "POST"
  allow: [ADMIN, MODERATOR, USER]
  redirect: "/site/login"


"/site/articles/get":
  controller: Articles
  action: getAllArticles
  method: "GET"




################## DYNAMIQUE PAGES #######################



